class AIS_System
{
    class AIS_System
    {
        file = "AIS\System";
        class postInit { postInit = 1; };
		class addMedEvacObj;
		class AIselfCheck;
		class allowCarry;
		class allowDrag;
		class allowPullIn;
		class allowPullOut;
		class allowRevive;
		class allowStabilize;
		class bloodloss;
		class bloodlossAI;
		class calculateLifeTime;
		class calculateReviveTime;
		class calculateStabilizeTime;
		class callHelp;
		class carry;
		class checkLauncher;
		class checkUnload;
		class diary;
		class disableRespawnButton;
		class drag;
		class findAIHelper;
		class getCargoIndex;
		class getOutMan;
		class handleHeal;
		class isMedic;
		class keyHandler;
		class killed;
		class loadAIS;
		class loadAISlocalToPlayer;
		class loadInjured;
		class medEvacArea;
		class moveAIHelper;
		class moveCargoRemote;
		class overrideHealAction;
		class release;
		class removeFaks;
		class respawn;
		class restoreFaks;
		class reveal;
		class Revive;
		class ReviveAI;
		class secondsToString;
		class setUnconscious;
		class stabilize;
		class unconcsiousRemote;
		class unconsciousAI;
		class unconsciousPlayer;
		class unloadInjured;
    };
};