_length = _this select 0;

_operation = "Operation ";
_first = "--blank--";

if (_length==0) then {
    _first_found = false;
    _first_dice = round (random 54);
    if (_first_dice<=1 AND !_first_found) then {_first_found=true;_first="Homing "};
    if (_first_dice==2 AND !_first_found) then {_first_found=true;_first="Flaming "};
    if (_first_dice==3 AND !_first_found) then {_first_found=true;_first="Screaming "};
    if (_first_dice==4 AND !_first_found) then {_first_found=true;_first="Final "};
    if (_first_dice==5 AND !_first_found) then {_first_found=true;_first="Fiery "};
    if (_first_dice==6 AND !_first_found) then {_first_found=true;_first="Brave "};
    if (_first_dice==7 AND !_first_found) then {_first_found=true;_first="Hardened "};
    if (_first_dice==8 AND !_first_found) then {_first_found=true;_first="Crazy "};
    if (_first_dice==9 AND !_first_found) then {_first_found=true;_first="Last "};
    if (_first_dice==10 AND !_first_found) then {_first_found=true;_first="Raging "};
    if (_first_dice==11 AND !_first_found) then {_first_found=true;_first="Blazing "};
    if (_first_dice==12 AND !_first_found) then {_first_found=true;_first="Covered "};
    if (_first_dice==13 AND !_first_found) then {_first_found=true;_first="Smoking "};
    if (_first_dice==14 AND !_first_found) then {_first_found=true;_first="Firing "};
    if (_first_dice==15 AND !_first_found) then {_first_found=true;_first="Mobile "};
    if (_first_dice==16 AND !_first_found) then {_first_found=true;_first="Crimson "};
    if (_first_dice==17 AND !_first_found) then {_first_found=true;_first="Broken "};
    if (_first_dice==18 AND !_first_found) then {_first_found=true;_first="Lightning "};
    if (_first_dice==19 AND !_first_found) then {_first_found=true;_first="Surviving "};
    if (_first_dice==20 AND !_first_found) then {_first_found=true;_first="Enduring "};
    if (_first_dice==21 AND !_first_found) then {_first_found=true;_first="Hunting "};
    if (_first_dice==22 AND !_first_found) then {_first_found=true;_first="Killing "};
    if (_first_dice==23 AND !_first_found) then {_first_found=true;_first="Fragging "};
    if (_first_dice==24 AND !_first_found) then {_first_found=true;_first="Overwhelming "};
    if (_first_dice==25 AND !_first_found) then {_first_found=true;_first="Thrusting "};
    if (_first_dice==26 AND !_first_found) then {_first_found=true;_first="Lone "};
    if (_first_dice==27 AND !_first_found) then {_first_found=true;_first="Armed "};
    if (_first_dice==28 AND !_first_found) then {_first_found=true;_first="Banned "};
    if (_first_dice==29 AND !_first_found) then {_first_found=true;_first="Sleeping "};
    if (_first_dice==30 AND !_first_found) then {_first_found=true;_first="Retired "};
    if (_first_dice==31 AND !_first_found) then {_first_found=true;_first="Retaliating "};
    if (_first_dice==32 AND !_first_found) then {_first_found=true;_first="Rushing "};
    if (_first_dice==33 AND !_first_found) then {_first_found=true;_first="Burning "};
    if (_first_dice==34 AND !_first_found) then {_first_found=true;_first="Striking "};
    if (_first_dice==35 AND !_first_found) then {_first_found=true;_first="Sweeping "};
    if (_first_dice==36 AND !_first_found) then {_first_found=true;_first="Masterful "};
    if (_first_dice==37 AND !_first_found) then {_first_found=true;_first="Mourning "};
    if (_first_dice==38 AND !_first_found) then {_first_found=true;_first="Black "};
    if (_first_dice==39 AND !_first_found) then {_first_found=true;_first="Yellow "};
    if (_first_dice==40 AND !_first_found) then {_first_found=true;_first="Purple "};
    if (_first_dice==41 AND !_first_found) then {_first_found=true;_first="Turquoise "};
    if (_first_dice==42 AND !_first_found) then {_first_found=true;_first="Red "};
    if (_first_dice==43 AND !_first_found) then {_first_found=true;_first="Green "};
    if (_first_dice==44 AND !_first_found) then {_first_found=true;_first="Blue "};
    if (_first_dice==45 AND !_first_found) then {_first_found=true;_first="Smashing "};
    if (_first_dice==46 AND !_first_found) then {_first_found=true;_first="Drowned "};
    if (_first_dice==47 AND !_first_found) then {_first_found=true;_first="Swift "};
    if (_first_dice==48 AND !_first_found) then {_first_found=true;_first="Courageous "};
    if (_first_dice==49 AND !_first_found) then {_first_found=true;_first="Fearful "};
    if (_first_dice==50 AND !_first_found) then {_first_found=true;_first="Barking "};
    if (_first_dice==51 AND !_first_found) then {_first_found=true;_first="Ruthless "};
    if (_first_dice==52 AND !_first_found) then {_first_found=true;_first="Rightful "};
    if (_first_dice==53 AND !_first_found) then {_first_found=true;_first="Hidden "};
    if (_first_dice==54 AND !_first_found) then {_first_found=true;_first="Marked "};
};

_second = "--blank--";
_second_found = false;
_second_dice = round (random 67);
if (_second_dice<=1 AND !_second_found) then {_second_found=true;_second="Switchblade"};
if (_second_dice==2 AND !_second_found) then {_second_found=true;_second="Knight"};
if (_second_dice==3 AND !_second_found) then {_second_found=true;_second="Guardian"};
if (_second_dice==4 AND !_second_found) then {_second_found=true;_second="Trident"};
if (_second_dice==5 AND !_second_found) then {_second_found=true;_second="Wraith"};
if (_second_dice==6 AND !_second_found) then {_second_found=true;_second="Rage"};
if (_second_dice==7 AND !_second_found) then {_second_found=true;_second="Hawk"};
if (_second_dice==8 AND !_second_found) then {_second_found=true;_second="Thunder"};
if (_second_dice==9 AND !_second_found) then {_second_found=true;_second="Poltergeist"};
if (_second_dice==10 AND !_second_found) then {_second_found=true;_second="Steel"};
if (_second_dice==11 AND !_second_found) then {_second_found=true;_second="Grave"};
if (_second_dice==12 AND !_second_found) then {_second_found=true;_second="Shield"};
if (_second_dice==13 AND !_second_found) then {_second_found=true;_second="Iron"};
if (_second_dice==14 AND !_second_found) then {_second_found=true;_second="Assault"};
if (_second_dice==15 AND !_second_found) then {_second_found=true;_second="Arrow"};
if (_second_dice==16 AND !_second_found) then {_second_found=true;_second="Bolt"};
if (_second_dice==17 AND !_second_found) then {_second_found=true;_second="Freedom"};
if (_second_dice==18 AND !_second_found) then {_second_found=true;_second="Sword"};
if (_second_dice==19 AND !_second_found) then {_second_found=true;_second="Lance"};
if (_second_dice==20 AND !_second_found) then {_second_found=true;_second="Witch"};
if (_second_dice==21 AND !_second_found) then {_second_found=true;_second="Nightmare"};
if (_second_dice==22 AND !_second_found) then {_second_found=true;_second="Force"};
if (_second_dice==23 AND !_second_found) then {_second_found=true;_second="Lion"};
if (_second_dice==24 AND !_second_found) then {_second_found=true;_second="Claw"};
if (_second_dice==25 AND !_second_found) then {_second_found=true;_second="Wolf"};
if (_second_dice==26 AND !_second_found) then {_second_found=true;_second="Blade"};
if (_second_dice==27 AND !_second_found) then {_second_found=true;_second="Sabre"};
if (_second_dice==28 AND !_second_found) then {_second_found=true;_second="Warrior"};
if (_second_dice==29 AND !_second_found) then {_second_found=true;_second="God"};
if (_second_dice==30 AND !_second_found) then {_second_found=true;_second="Cannon"};
if (_second_dice==31 AND !_second_found) then {_second_found=true;_second="Vengeance"};
if (_second_dice==32 AND !_second_found) then {_second_found=true;_second="Dagger"};
if (_second_dice==33 AND !_second_found) then {_second_found=true;_second="Fist"};
if (_second_dice==34 AND !_second_found) then {_second_found=true;_second="Warlock"};
if (_second_dice==35 AND !_second_found) then {_second_found=true;_second="Copper"};
if (_second_dice==36 AND !_second_found) then {_second_found=true;_second="Bronze"};
if (_second_dice==37 AND !_second_found) then {_second_found=true;_second="Talon"};
if (_second_dice==38 AND !_second_found) then {_second_found=true;_second="Viper"};
if (_second_dice==39 AND !_second_found) then {_second_found=true;_second="Cobra"};
if (_second_dice==40 AND !_second_found) then {_second_found=true;_second="Falcon"};
if (_second_dice==41 AND !_second_found) then {_second_found=true;_second="Eagle"};
if (_second_dice==42 AND !_second_found) then {_second_found=true;_second="Onslaught"};
if (_second_dice==43 AND !_second_found) then {_second_found=true;_second="Phoenix"};
if (_second_dice==44 AND !_second_found) then {_second_found=true;_second="Raven"};
if (_second_dice==45 AND !_second_found) then {_second_found=true;_second="Dragon"};
if (_second_dice==46 AND !_second_found) then {_second_found=true;_second="Crusader"};
if (_second_dice==47 AND !_second_found) then {_second_found=true;_second="Devil"};
if (_second_dice==48 AND !_second_found) then {_second_found=true;_second="Angel"};
if (_second_dice==49 AND !_second_found) then {_second_found=true;_second="Hammer"};
if (_second_dice==50 AND !_second_found) then {_second_found=true;_second="Cleaver"};
if (_second_dice==51 AND !_second_found) then {_second_found=true;_second="Nova"};
if (_second_dice==52 AND !_second_found) then {_second_found=true;_second="Marauder"};
if (_second_dice==53 AND !_second_found) then {_second_found=true;_second="Dart"};
if (_second_dice==54 AND !_second_found) then {_second_found=true;_second="Rodent"};
if (_second_dice==55 AND !_second_found) then {_second_found=true;_second="Swordfish"};
if (_second_dice==56 AND !_second_found) then {_second_found=true;_second="Boar"};
if (_second_dice==57 AND !_second_found) then {_second_found=true;_second="Rhino"};
if (_second_dice==58 AND !_second_found) then {_second_found=true;_second="Shark"};
if (_second_dice==59 AND !_second_found) then {_second_found=true;_second="Goul"};
if (_second_dice==60 AND !_second_found) then {_second_found=true;_second="Anvil"};
if (_second_dice==61 AND !_second_found) then {_second_found=true;_second="Star"};
if (_second_dice==62 AND !_second_found) then {_second_found=true;_second="Sun"};
if (_second_dice==63 AND !_second_found) then {_second_found=true;_second="Morgenstern"};
if (_second_dice==64 AND !_second_found) then {_second_found=true;_second="Gladius"};
if (_second_dice==65 AND !_second_found) then {_second_found=true;_second="Chieftain"};
if (_second_dice==66 AND !_second_found) then {_second_found=true;_second="Spirit"};
if (_second_dice==67 AND !_second_found) then {_second_found=true;_second="Paladin"};

if (_length==1) exitWith {
    _second
};

if (_length==0) then {
    _gen_operation_fullname = _operation+_first+_second;
    _gen_operation_fullname
};